- src/SaraWeeklyTasks/Week01/OddEven.java
> Sara-folder

- src/raminaWeeklyTasks/OddOrEven.java
> OddOrEven task uploaded

- src/raminaWeeklyTasks/OddOrEven.java
> OddOrEven task solved

- src/halnurWeeklyTasks/week01/OddOrEven.java
> added identify method.

- src/mahdiweeklytasks/week01/OddOrEven.java
Please see my recent codes and let me now if there is any issue
> Week01Task Add

- src/troyWeeklyTasks/Week01/OddOrEven.java
- src/troyWeeklyTasks/Week02/Number_FINRA_DivisibleBy3_5.java
> week02 task added

- src/troyWeeklyTasks/Week01/OddOrEven.java
> week01 solutions added

- src/troyWeeklyTasks/Week03/SwapTwoNumbers.java
> week03 task added

- src/SaraWeeklyTasks/Week02/Number_FINRA_DivisibleBy3_5.java
I've done just a minor change.
> I added practice description to the beginning of the code

- src/halnurWeeklyTasks/week03/SwapTwoNumbers.java
> Swap two number

- src/raminaWeeklyTasks/week03/SwapTwoNumbers.java
added SwapTwoNumbers task solution. Please review and let me know if anything looks wrong
> Week 03 task

- src/troyWeeklyTasks/Week04/Number_ReverseNegative_W4.java
> week04 task added

- src/halnurWeeklyTasks/week04/Number_ReverseNegative_W4.java
Please check solution of reverese negative number
> Reverse negative number

- src/halnurWeeklyTasks/week04/Number_ReverseNegative_W4.java
I removed the previous if statement part.
> Reverse negative number(deleted if statement)

- src/halnurWeeklyTasks/week04/Number_ReverseNegative_W4.java
Sorry,I don't change any more:)
> Reverse negative number(Final)

- src/troyWeeklyTasks/Week04/Number_ReverseNegative_W4.java
- src/troyWeeklyTasks/Week05/FrequencyOfChars.java
Please see week4 solution and week5 task
> week05 task added and also week4 solution

- src/SaraWeeklyTasks/Week03/SwapTwoNumbers.java
- src/SaraWeeklyTasks/week04/Number_ReverseNegative_W4.java
- src/SaraWeeklyTasks/week05/FrequencyOfChars.java
> I deleted extra spaces on Swap Two Number. Also I add Negative Number Reverse.

- src/halnurWeeklyTasks/week05/FrequencyOfChars.java
> FrequencyOfChars method

- src/raminaWeeklyTasks/week05/FrequencyOfChars.java
> Week 05 task solution

- src/halnurWeeklyTasks/week06/RemoveDuplicates.java
Added week06 task. check please.
> RemoveDuplicates method(Halnur)

- src/Lejlas_Weekly_Task/week6/RemoveDuplicates.java
My solution to **RemoveDuplicates**
> Remove Duplicates -Lejla

- src/Lejlas_Weekly_Task/week7/FindUniqueChars.java
> Find Unique Char -Lejla

- src/raminaWeeklyTasks/week07/FindUniqueChars.java
I added FindUniqueChars task solution
> Week 07 task solution

- src/halnurWeeklyTasks/week07/FindUniqueChars.java
> FindUniqueChars method(Halnur)

- src/raminaWeeklyTasks/week09/PasswordValidation.java
- src/raminaWeeklyTasks/week10/FindMinArray.java
Password Validation and Find Minimum Array tasks solutions added. please review
> Week 09, 10 tasks solutions

- src/halnurWeeklyTasks/week11/MoveZerosToEnd.java
Please check MoveZerosToEnd method .
> week11(Halnur)

- src/raminaWeeklyTasks/week11/MoveZerosToEnd.java
Added MoveZerosToEnd task solution
> Week11 task solution

- src/raminaWeeklyTasks/week12/SortArrayAsc.java
SortArrayInAsc task solution is added, please review
> Week 12 task solution

- src/mahdiWeeklyTasks/week05/CharacterFrequency.java
> week05 CharacterFrequency
